#!/bin/bash

function open_browser {
    arr=$@
    for url in $arr; do
        google-chrome $url
    done
}

function open_jupyter {
    project=$1
    jupyter notebook $project
}

function open_vscodes {
    projs=$@
    for p in $projs; do
        code $p
    done
}