#!/bin/bash
source ./functions

urls=(
    https://gitlab.com/reformma
    https://reformma.com.br/
    https://app.slack.com/client/TLD2BS8FL/
    https://analytics.google.com/analytics/web/
    https://console.firebase.google.com/u/0/project/reformma-ee9b3/overview
)

vscodes_projs=(
    ~/reformma/normma/ 
    ~/reformma/gringotts/ 
    ~/reformma/fundaccao/ 
)

open_vscodes "${vscodes_projs[@]}"
open_browser "${urls[@]}"